// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace URS.ClientKit
{
    public static unsafe partial class FFIWrap
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "clientkit";
#endif
        



        [DllImport(__DllName, EntryPoint = "UTF16String_Extern", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void UTF16String_Extern(UTF16String value);

        [DllImport(__DllName, EntryPoint = "free_c_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void free_c_string(byte* str);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct UTF16String
    {
        public ushort* ptr;
        public uint len;
    }



}
    