// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace URS.ClientKit
{
    internal static unsafe partial class DebugWrap
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "clientkit";
#endif
        



        [DllImport(__DllName, EntryPoint = "BindUnityEngineDebugLog", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void BindUnityEngineDebugLog(delegate* unmanaged[Cdecl]<byte*, void> func);

        [DllImport(__DllName, EntryPoint = "BindUnityEngineDebugWarning", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void BindUnityEngineDebugWarning(delegate* unmanaged[Cdecl]<byte*, void> func);

        [DllImport(__DllName, EntryPoint = "BindUnityEngineDebugError", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void BindUnityEngineDebugError(delegate* unmanaged[Cdecl]<byte*, void> func);


    }



}
    