// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace URS.ClientKit
{
    internal static unsafe partial class ZipArchiveWrap
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "clientkit";
#endif
        



        [DllImport(__DllName, EntryPoint = "ZipArchive_New", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ZipArchivePtr* ZipArchive_New(UTF16String archive_path);

        [DllImport(__DllName, EntryPoint = "ZipArchive_FileExist", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool ZipArchive_FileExist(ZipArchivePtr* ptr, UTF16String file_path);

        [DllImport(__DllName, EntryPoint = "ZipArchive_Open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ZipFilePtr* ZipArchive_Open(ZipArchivePtr* ptr, UTF16String file_path);

        [DllImport(__DllName, EntryPoint = "ZipArchive_ReadAllBytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ByteBuffer* ZipArchive_ReadAllBytes(ZipArchivePtr* ptr, UTF16String file_path);

        [DllImport(__DllName, EntryPoint = "ZipArchive_Dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void ZipArchive_Dispose(ZipArchivePtr* ptr);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ZipArchivePtr
    {
    }



}
    