// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace URS.ClientKit
{
    internal static unsafe partial class ZipFileWrap
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "clientkit";
#endif
        



        [DllImport(__DllName, EntryPoint = "ZipFile_Length", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long ZipFile_Length(ZipFilePtr* ptr);

        [DllImport(__DllName, EntryPoint = "ZipFile_Seek", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long ZipFile_Seek(ZipFilePtr* ptr, long offset, SeekOrigin seek_origin);

        [DllImport(__DllName, EntryPoint = "ZipFile_Position", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long ZipFile_Position(ZipFilePtr* ptr, long offset, SeekOrigin seek_origin);

        [DllImport(__DllName, EntryPoint = "ZipFile_Read", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ByteBuffer* ZipFile_Read(ZipFilePtr* ptr, int length);

        [DllImport(__DllName, EntryPoint = "ZipFile_Dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void ZipFile_Dispose(ZipFilePtr* ptr);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ZipFilePtr
    {
    }


    internal enum SeekOrigin : byte
    {
        Begin = 0,
        Current = 1,
        End = 2,
    }


}
    