// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace URS.ClientKit
{
    internal static unsafe partial class DownloadServiceWrap
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "clientkit";
#endif
        



        [DllImport(__DllName, EntryPoint = "DownloadService_Start", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern DownloadServicePtr* DownloadService_Start([MarshalAs(UnmanagedType.U1)] bool multi_thread, ushort thread_count, ushort parallel_count);

        [DllImport(__DllName, EntryPoint = "DownloadService_SetParallelCount", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void DownloadService_SetParallelCount(DownloadServicePtr* ptr, ushort count);

        [DllImport(__DllName, EntryPoint = "DownloadService_Stop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void DownloadService_Stop(DownloadServicePtr* ptr);

        [DllImport(__DllName, EntryPoint = "DownloadService_AddDownload", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern DownloadOperationPtr* DownloadService_AddDownload(DownloadServicePtr* ptr, DownloadConfig config);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct DownloadServicePtr
    {
    }



}
    